In [1]:
import pickle
import torch
import os

/home/yatin/miniconda3/envs/ilploss/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
cd ../../data

/home/yatin/btech/cs1180416/btp/data


In [4]:
ls -ltrh

total 840M
-rwxrwxrwt 1 89667 10951 190K Oct 21  2021 random_16x16_1k.pt*
-rwxrwxrwt 1 89667 10951  80K Oct 27  2021 random_2x16_1k.pt*
-rwxrwxrwt 1 89667 10951 784K Oct 28  2021 random_8x16_10k.pt*
-rwxrwxrwt 1 89667 10951 352K Jan  3  2022 sudoku_2x4_2805.pt*
drwxrwxrwt 1 89667 10951 4.0K Jan 10  2022 mnist/
drwxrwxrwt 1 89667 10951 4.0K Jan 12  2022 vis_sudoku/
drwxrwxrwt 1 89667 10951 4.0K Mar 31 12:46 graph-matching-data/
-rwxrwxrwt 1 89667 10951 3.3M Apr 22 17:06 sudoku_3x4_11760.pt*
-rwxrwxrwt 1 89667 10951  31M Apr 23 01:16 sudoku_2x2_1M.pt.backup*
-rwxrwxrwt 1 89667 10951 790K Apr 23 01:40 sudoku_2x3_11214.pt.backup*
-rwxrwxrwt 1 89667 10951 155M Apr 23 01:42 sudoku_3x3_1M_canon.pt.backup*
-rwxrwxrwt 1 89667 10951 790K Apr 23 01:49 sudoku_2x3_11214.pt*
-rwxrwxrwt 1 89667 10951 155M Apr 23 01:54 sudoku_3x3_1M_relabeled.pt*
-rwxrwxrwt 1 89667 10951 155M Apr 23 01:54 sudoku_3x3_1M.pt.backup*
lrwxrwxrwx 1 89667 10951   54 Apr 27 16:16 comboptnet-data -> /home/rishabh/yatin_scratch

In [27]:
canon = 'sudoku_3x3_1M_canon.pt'
backup = 'sudoku_3x3_1M.pt.backup'
original = 'sudoku_3x3_1M.pt'

In [28]:
can = torch.load(canon)

In [29]:
back  = torch.load(backup)

In [30]:
orig = torch.load(original)

In [9]:
len(can)

4

In [31]:
orig['y'][0].reshape(9,9)

tensor([[1, 2, 9, 7, 3, 6, 4, 8, 5],
        [8, 6, 7, 4, 5, 2, 9, 3, 1],
        [3, 5, 4, 9, 1, 8, 6, 7, 2],
        [4, 7, 8, 1, 6, 3, 2, 5, 9],
        [6, 1, 3, 2, 9, 5, 8, 4, 7],
        [5, 9, 2, 8, 4, 7, 1, 6, 3],
        [2, 3, 1, 5, 8, 4, 7, 9, 6],
        [9, 4, 6, 3, 7, 1, 5, 2, 8],
        [7, 8, 5, 6, 2, 9, 3, 1, 4]], dtype=torch.uint8)

In [15]:
can['y'][0].reshape(9,9)

tensor([[1, 2, 3, 6, 7, 5, 9, 4, 8],
        [4, 5, 6, 9, 8, 2, 3, 7, 1],
        [7, 8, 9, 3, 1, 4, 5, 6, 2],
        [9, 6, 4, 1, 5, 7, 2, 8, 3],
        [5, 1, 7, 2, 3, 8, 4, 9, 6],
        [8, 3, 2, 4, 9, 6, 1, 5, 7],
        [2, 7, 1, 8, 4, 9, 6, 3, 5],
        [3, 9, 5, 7, 6, 1, 8, 2, 4],
        [6, 4, 8, 5, 2, 3, 7, 1, 9]], dtype=torch.uint8)

In [33]:
back['y'][0].reshape(9,9)

tensor([[1, 2, 3, 6, 7, 5, 9, 4, 8],
        [4, 5, 6, 9, 8, 2, 3, 7, 1],
        [7, 8, 9, 3, 1, 4, 5, 6, 2],
        [9, 6, 4, 1, 5, 7, 2, 8, 3],
        [5, 1, 7, 2, 3, 8, 4, 9, 6],
        [8, 3, 2, 4, 9, 6, 1, 5, 7],
        [2, 7, 1, 8, 4, 9, 6, 3, 5],
        [3, 9, 5, 7, 6, 1, 8, 2, 4],
        [6, 4, 8, 5, 2, 3, 7, 1, 9]], dtype=torch.uint8)

In [25]:
(can['y'] == back['y']).all()

tensor(True)

In [26]:
(can['x'] == back['x']).all()

tensor(True)

In [24]:
print(can['meta'].__doc__)

dict() -> new empty dictionary
dict(mapping) -> new dictionary initialized from a mapping object's
    (key, value) pairs
dict(iterable) -> new dictionary initialized as if via:
    d = {}
    for k, v in iterable:
        d[k] = v
dict(**kwargs) -> new dictionary initialized with the name=value pairs
    in the keyword argument list.  For example:  dict(one=1, two=2)


In [45]:
cd data_for_output-space-inv

/home/yatin/softlinks/shiva_home/data_for_output-space-inv


In [51]:
su_test = 'sudoku_9_all_unq_test.pkl'
su_train = 'sudoku_9_train_e_unq_10k.pkl'
su_val ='sudoku_9_val_e_big_unique.pkl'

In [52]:
with open(su_test,'rb') as fh:
    su_test = pickle.load(fh)

In [53]:
with open(su_train,'rb') as fh:
    su_train = pickle.load(fh)

In [54]:
with open(su_val,'rb') as fh:
    su_val = pickle.load(fh)

In [67]:
su_val[0]

{'query': array([8, 3, 6, 0, 0, 0, 0, 4, 9, 0, 7, 0, 4, 2, 8, 0, 0, 0, 0, 5, 0, 6,
        0, 0, 1, 0, 8, 9, 0, 0, 0, 3, 0, 5, 1, 0, 0, 0, 0, 5, 8, 0, 6, 0,
        2, 0, 2, 0, 0, 4, 0, 7, 0, 0, 0, 9, 0, 7, 0, 0, 8, 0, 5, 4, 8, 0,
        0, 0, 0, 0, 0, 0, 3, 0, 5, 0, 0, 9, 4, 0, 0], dtype=int8),
 'target_set': [array([8, 3, 6, 1, 7, 5, 2, 4, 9, 1, 7, 9, 4, 2, 8, 3, 5, 6, 2, 5, 4, 6,
         9, 3, 1, 7, 8, 9, 6, 8, 2, 3, 7, 5, 1, 4, 7, 4, 3, 5, 8, 1, 6, 9,
         2, 5, 2, 1, 9, 4, 6, 7, 8, 3, 6, 9, 2, 7, 1, 4, 8, 3, 5, 4, 8, 7,
         3, 5, 2, 9, 6, 1, 3, 1, 5, 8, 6, 9, 4, 2, 7], dtype=int8)],
 'count': 1}

In [57]:
import random

In [58]:
random.shuffle(su_train)

In [59]:
random.shuffle(su_val)

In [60]:
random.shuffle(su_test)

In [61]:
su_all = su_train + su_val + su_test

In [56]:
len(su_all)

33000

In [64]:
with open('sudoku_9_unq_train10k_val5k_test18k.pkl','wb') as fh:
    pickle.dump(su_all, fh)

In [63]:
len(su_train), len(su_val), len(su_test)

(10000, 5000, 18000)

In [68]:
pwd

'/home/yatin/softlinks/shiva_home/data_for_output-space-inv'

In [70]:
cd hpchome/phd/comboptnet/

/home/yatin/softlinks/hpchome/phd/comboptnet


In [4]:
cd /home/yatin/softlinks/hpchome/phd/comboptnet/neurips_sudoku/data/yatin_sudoku_visual_ilploss_2x3_version_8_pred_0-499

/home/yatin/btech/cs1180416/btp/data/yatin_sudoku_visual_ilploss_2x3_version_8_pred_0-499


In [108]:
cd /home/yatin/softlinks/hpchome/phd/comboptnet/neurips_sudoku/rishabh_runs/neurips/sudoku/symbolic/ilploss/3x3_canon/version_7/pred_0-499

/home/yatin/btech/cs1180416/btp/runs/neurips/sudoku/symbolic/ilploss/3x3_canon/version_7/pred_0-499


In [2]:
cd /home/yatin/softlinks/hpchome/phd/comboptnet/neurips_sudoku/rishabh_runs/neurips/sudoku/symbolic/ilploss/2x3/version_11/pred_0-499

/home/yatin/btech/cs1180416/btp/runs/neurips/sudoku/symbolic/ilploss/2x3/version_11/pred_0-499


In [125]:
cd /home/yatin/softlinks/hpchome/phd/comboptnet/neurips_sudoku/rishabh_runs/neurips/sudoku/symbolic/ilploss/2x3/version_11/pred_0-499

/home/yatin/btech/cs1180416/btp/runs/neurips/sudoku/symbolic/ilploss/2x3/version_11/pred_0-499


In [2]:
cd /home/yatin/softlinks/hpchome/phd/comboptnet/neurips_sudoku/runs/neurips/sudoku/visual/ilploss/3x3_canon/eq_onsatnetdata/version_1/pred

/home/yatin/softlinks/hpcscratch/comboptnet/runs/neurips/sudoku/visual/ilploss/3x3_canon/eq_onsatnetdata/version_1/pred


In [7]:
cd /home/yatin/hpchome/phd/combboptnet/neurips_sudoku/runs/neurips/sudoku/visual/ilploss/3x3_satnet/eq/version_0/pred

/home/yatin/softlinks/hpcscratch/comboptnet/runs/neurips/sudoku/visual/ilploss/3x3_satnet/eq/version_0/pred


In [13]:
cd /home/yatin/softlinks/hpchome/phd/comboptnet/neurips_sudoku/rishabh_runs/neurips/knapsack/binary/comboptnet/items_25/seed_0/version_2/pred

/home/yatin/btech/cs1180416/btp/runs/neurips/knapsack/binary/comboptnet/items_25/seed_0/version_2/pred


In [6]:
cd /home/yatin/softlinks/hpchome/phd/comboptnet/neurips_sudoku/rishabh_runs/neurips/knapsack/binary/comboptnet/items_30/seed_0/version_2/pred

/home/yatin/btech/cs1180416/btp/runs/neurips/knapsack/binary/comboptnet/items_30/seed_0/version_2/pred


In [28]:
acc = {}
missing_task = []

import numpy as np
import tqdm

for this_task in os.listdir('.'):
    yhat_file_list = [x for x in os.listdir(this_task) if x.endswith('_yhat.npy')]
    if len(yhat_file_list) > 0:
        yhat = np.load(os.path.join(this_task,yhat_file_list[0]))
        y = np.load(os.path.join(this_task,'y.npy'))
        acc[this_task] = int((y==yhat).all())
    else:
        #print('missing', this_task)
        missing_task.append(this_task)


total_samples = len(acc) + len(missing_task)
print("Accuracy: ", sum(acc.values())/total_samples)

Accuracy:  0.042


In [29]:
print("Missing count: ", len(missing_task))

Missing count:  0


In [30]:
len(acc), sum(acc.values())/len(acc)

(500, 0.042)

In [31]:
sum(acc.values())

21

In [27]:
22/500

0.044

In [11]:
[(k,v) for k,v in acc.items() if v == 0]

[('661', 0),
 ('815', 0),
 ('202', 0),
 ('802', 0),
 ('86', 0),
 ('994', 0),
 ('984', 0),
 ('257', 0),
 ('558', 0),
 ('712', 0),
 ('493', 0),
 ('156', 0),
 ('282', 0),
 ('954', 0),
 ('989', 0),
 ('536', 0),
 ('112', 0)]